# Generated by Django 5.0.4 on 2024-04-20 04:35

import offices.managers.UserManager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', offices.managers.UserManager.UsersManager()),
            ],
        ),
    ]
