# Generated by Django 5.0.4 on 2024-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True),
        ),
    ]
