# Generated by Django 5.0.4 on 2024-04-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_alter_order_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='order_id',
        ),
    ]
