# Generated by Django 5.0.4 on 2024-04-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_ordertoauthor_order_author_id_ordertoexecutor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderToexEcutor',
            new_name='OrderToEcutor',
        ),
    ]
